spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      path: /console
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none










