
drop table if exists category CASCADE;

drop table if exists item CASCADE ;

create table category (
                            category_id bigint generated by default as identity,
                            name varchar(50) not null,
                            primary key (category_id)
                        );

create table item (
                       id bigint generated by default as identity,
                       active boolean not null,
                       date_created timestamp,
                       date_updated timestamp,
                       description varchar(90) not null,
                       image varchar(255) not null,
                       name varchar(50) not null,
                       price decimal(19,2) not null,
                       category_id bigint not null,
                       primary key (id)
                   );

alter table item
    add constraint FK2n9w8d0dp4bsfra9dcg0046l4 foreign key (category_id) references category;
